export const ADD_TODO = 'ADD_TODO';
export const LOADING_TODOS_START = 'LOADING_TODOS_START';
export const LOADING_TODOS_SUCCESS = 'LOADING_TODOS_SUCCESS';
export const LOADING_TODOS_FAILED = 'LOADING_TODOS_FAILED';
export const REMOVE_TODO = 'REMOVE_TODO';
export const UPDATE_CHECKBOX = 'UPDATE_CHECKBOX';
export const DELETE_ALL = 'DELETE_ALL';